openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /api/register:
    post:
      summary: Register a new member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: string
                pwd:
                  type: string
                pwd_confirm:
                  type: string
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "ok"
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      id:
                        type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "이미 존재하는 아이디입니다."
        '500':
          description: Database error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Database error"

  /api/login:
    post:
      summary: Log in an existing member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                pwd:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "ok"
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      id:
                        type: string
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Invalid ID or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "아이디 또는 비밀번호가 일치하지 않습니다."
        '500':
          description: Database error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Database error"

  /api/update-password:
    post:
      summary: Update password for logged-in user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pwd:
                  type: string
                  description: "New password"
                pwd_confirm:
                  type: string
                  description: "Confirm new password"
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "ok"
                  message:
                    type: string
                    example: "비밀번호가 성공적으로 변경되었습니다."
        '400':
          description: Password mismatch or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "비밀번호가 일치하지 않습니다."
        '500':
          description: Database error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Database error"

  /api/delete-account:
    post:
      summary: Delete account for logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Account deletion successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "ok"
                  message:
                    type: string
                    example: "회원 탈퇴가 완료되었습니다."
        '401':
          description: Unauthorized - Token missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "유효하지 않은 토큰입니다."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "회원 탈퇴 중 오류가 발생했습니다."

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
